#!/usr/bin/env python3
"""Generate ship sprites and heading tables for battleships.c.

Writes src/c/ship_sprites.h with:
  ship_frames   HEADINGS sprites (63 bytes each), heading 0 = east, then
                clockwise (screen y points down) in STEP-degree steps
  head_x/head_y unit heading vector * 32
  bow_x/bow_y   bow offset from the ship centre in pixels

Each sprite pixel is 4x4 supersampled against the east-facing hull art and
set when at least half of it is covered, which keeps rotations clean.

Usage: gen_ship_sprites.py [output.h] [--preview sheet.png]
"""
import math
import struct
import sys
import zlib

HEADINGS = 36
STEP = 360 // HEADINGS
BOW_LEN = 9          # pixels from centre to bow (and stern) collision points
SUB = 4              # supersampling per axis

# East-facing hull, rows 7..13 of a 21x21 box centred on (10,10).
HULL = [
    "..###########........",
    ".###############.....",
    "####.##.#####.#####..",
    "###...#...#...#######",
    "####.##.#####.#####..",
    ".###############.....",
    "..###########........",
]
HULL_TOP = 7


def hull_at(u, v):
    """Hull art pixel containing point (u, v) in art coordinates."""
    x = math.floor(u + 0.5)
    y = math.floor(v + 0.5) - HULL_TOP
    if 0 <= y < len(HULL) and 0 <= x < len(HULL[0]):
        return HULL[y][x] == "#"
    return False


def render(deg):
    """Returns a 21x21 list of rows of 0/1 for the ship at heading deg."""
    c = math.cos(math.radians(deg))
    s = math.sin(math.radians(deg))
    img = []
    for y in range(21):
        row = []
        for x in range(21):
            hits = 0
            for sy in range(SUB):
                for sx in range(SUB):
                    dx = x - 10 + (sx + 0.5) / SUB - 0.5
                    dy = y - 10 + (sy + 0.5) / SUB - 0.5
                    # rotate the screen offset back into the east-facing art
                    u = dx * c + dy * s
                    v = -dx * s + dy * c
                    hits += hull_at(10 + u, 10 + v)
            row.append(1 if hits * 2 >= SUB * SUB else 0)
        img.append(row)
    return img


def sprite_bytes(img):
    out = []
    for y in range(21):
        bits = img[y] + [0] * 3          # 24 pixels wide
        for b in range(3):
            v = 0
            for i in range(8):
                v = (v << 1) | bits[b * 8 + i]
            out.append(v)
    return out


def c_array(name, ctype, values, per_line=16):
    lines = []
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        if ctype.startswith("unsigned"):
            lines.append("    " + ", ".join(f"0x{v:02X}" for v in chunk) + ",")
        else:
            lines.append("    " + ", ".join(f"{v:4d}" for v in chunk) + ",")
    return f"static const {ctype} {name}[{len(values)}] = {{\n" + "\n".join(lines) + "\n};\n"


def write_png(path, rows):
    h = len(rows)
    w = len(rows[0])
    raw = b"".join(b"\x00" + bytes(r) for r in rows)

    def chunk(t, d):
        return struct.pack(">I", len(d)) + t + d + struct.pack(">I", zlib.crc32(t + d) & 0xFFFFFFFF)

    png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 0, 0, 0, 0))
    png += chunk(b"IDAT", zlib.compress(raw)) + chunk(b"IEND", b"")
    open(path, "wb").write(png)


def main():
    args = sys.argv[1:]
    preview = None
    if "--preview" in args:
        i = args.index("--preview")
        preview = args[i + 1]
        del args[i:i + 2]
    out = args[0] if args else "src/c/ship_sprites.h"

    frames = [render(d * STEP) for d in range(HEADINGS)]
    data = [b for img in frames for b in sprite_bytes(img)]
    head_x = [round(32 * math.cos(math.radians(d * STEP))) for d in range(HEADINGS)]
    head_y = [round(32 * math.sin(math.radians(d * STEP))) for d in range(HEADINGS)]
    bow_x = [round(BOW_LEN * math.cos(math.radians(d * STEP))) for d in range(HEADINGS)]
    bow_y = [round(BOW_LEN * math.sin(math.radians(d * STEP))) for d in range(HEADINGS)]

    with open(out, "w") as f:
        f.write("/* Generated by tools/gen_ship_sprites.py - do not edit. */\n\n")
        f.write(f"#define HEADINGS {HEADINGS}           /* {STEP} degrees each, 0 = east, clockwise */\n\n")
        f.write("/* 63 bytes per heading */\n")
        f.write(c_array("ship_frames", "unsigned char", data, 21))
        f.write("\n/* unit heading vector * 32 */\n")
        f.write(c_array("head_x", "signed char", head_x, 12))
        f.write(c_array("head_y", "signed char", head_y, 12))
        f.write(f"\n/* bow offset from ship centre, pixels */\n")
        f.write(c_array("bow_x", "signed char", bow_x, 12))
        f.write(c_array("bow_y", "signed char", bow_y, 12))

    if preview:
        # 9 x 4 sheet, 3x scale, 1 px grid
        cols, scale, cell = 9, 3, 21 * 3 + 2
        rows = [[40] * (cols * cell) for _ in range((HEADINGS // cols) * cell)]
        for i, img in enumerate(frames):
            ox, oy = (i % cols) * cell + 1, (i // cols) * cell + 1
            for y in range(21):
                for x in range(21):
                    v = 255 if img[y][x] else 0
                    for yy in range(scale):
                        for xx in range(scale):
                            rows[oy + y * scale + yy][ox + x * scale + xx] = v
        write_png(preview, rows)


if __name__ == "__main__":
    main()
